# Generated by Django 3.1.2 on 2020-10-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='photo',
            field=models.ImageField(blank=True, default='avatars/none/default.png', height_field='image_height', null=True, upload_to='media/photo/', width_field='image_width'),
        ),
    ]
