# Generated by Django 3.1.2 on 2020-10-25 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_task_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='sonuc',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='task',
            name='photo',
            field=models.ImageField(blank=True, default='avatars/none/default.png', null=True, upload_to='media/photo/'),
        ),
    ]
