# Generated by Django 3.1.2 on 2020-10-25 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201025_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='sonuc',
        ),
    ]
