# Generated by Django 3.1.2 on 2020-10-25 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_task_sonuc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='photo',
        ),
        migrations.AddField(
            model_name='task',
            name='photo_url',
            field=models.ImageField(blank=True, null=True, upload_to='media/photo/'),
        ),
    ]
