# Generated by Django 3.1.2 on 2020-10-25 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201025_1942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='photo_url',
            new_name='photo',
        ),
    ]
