# Generated by Django 3.1.2 on 2020-10-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20201025_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deneme',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='photo',
            field=models.ImageField(default=1, upload_to='media/photo/'),
            preserve_default=False,
        ),
    ]
