# Generated by Django 3.1.2 on 2020-10-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20201027_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='photo',
        ),
        migrations.AddField(
            model_name='task',
            name='deneme',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
